### ISSUE TITLE
Verwendung in Isotope Bestellbedingungsformular geht nicht mehr

### ISSUE THREAD

**Issue by cs1982** [christianbarkowsky/contao-extended-checkbox#1]
Schon mit Contao 2.11.9, Isotope 1.4.7 und Extended Checkbox 1.0.2 stable Build 8 habe ich Extended Checkbox im Bestellbedingungsformular (eingebettet im letzten Schritt der Isotope Kasse) ohne Probleme verwendet. Das sieht man, wenn man eine testweise Gastbestellung in meinem Shop erstellt und bis zum letzten Schritt des Checkout als Gast durchklickt ohne zu bestellen: https://www.mit-liebe-gebacken.de/online-shop.html

Nun arbeite ich daran, meine Umgebung auf Contao 3.5.2 und Isotope 2.3.0 stable zu aktualisieren. Ich verwende dabei Extended Checkbox 1.1.3.9003.
Nach der Installation von Isotope 2.3.0 stable habe ich in meiner Entwicklungsumgebung seit längerem (meint seit der Installation von mehreren Vorversionen von C, I und ECB) mal wieder eine vollständige Bestellung durchgeklickt und die Bestellung lässt sich einfach nicht abschließen. Seit welchem Versionsstand das so ist, kann ich sicher nicht sagen.
Darauf hin habe ich folgendes Ticket erstellt: https://github.com/isotope/core/issues/1524

Nach einigen Anläufen habe ich endlich die Stelle gefunden, die mit dem Problem unmittelbar zusammen hängt - die Erweiterten Checkboxen im Bestellbedingungformular. Wenn ich die deaktiviere, geht es sofort. Ich weis nicht, ob ECB oder Isotope das Problem verursacht, aber es wäre toll, wenn das behoben würde.

**Comment by cs1982** [comment]
Unkommentiert schließen  - das spricht für sich. Für andere mit dem gleichen Problem: Glücklicherweise ist ein Link in einem Checkbox-Label auch über einen Inserttag abbildbar. Damit kann man die Erweiterung deinstallieren, wenn Sie nur im beschriebenen Kontext verwendet wird.

https://docs.contao.org/books/manual/3.5/de/04-inhalte-verwalten/inserttags.html
{{link_url::12}}, lässt sich auch mit target="_blank" kombinieren.

**Comment by christianbarkowsky** [comment]
Ist Montag was. :)

Du kannst die Erweiterung gern deinstallieren ... aber du kannst auch gern mal anrufen oder uns per skype anschreiben.
