### ISSUE TITLE
PLS use the new form_row template in Contao 3.5.x

### ISSUE THREAD

**Issue by MacKP** [christianbarkowsky/contao-extended-checkbox#2]
It would be nice, if the new templates where used by this extension ;-)

regards

**Comment by MacKP** [comment]
oh, sorry found <?php $this->extend('form_row'); ?> so it should be right.
I think my Problem is in the form_widget_extended_checkbox_without_label.html5 ^^

regards

**Comment by MacKP** [comment]
Hm I realy tryed to figure this out... but something is strange. It doesn't take the form_row template as far as I see. Can you have a look at the generating of the HTML with the templates? It also can be that I am missing something important... 
regards

**Comment by christianbarkowsky** [comment]
@MacKP just try the develop branch
