### ISSUE TITLE
Contao 4

### ISSUE THREAD

**Issue by m-vo** [christianbarkowsky/contao-extended-checkbox#3]
Any plans on supporting 4.*? 
:-)

**Comment by christianbarkowsky** [comment]
@m-vo yes of course

**Comment by Schmidty2** [comment]
+1

**Comment by Schmidty2** [comment]
Ich habe heute die extented Ceckbox manuell unter Contao 4.4.3 und PHP 7.0 installiert. Bisher konnte ich keinen Fehler feststellen.

Ist es möglich, die Erweiterung in den nächsten ein bis zwei Wochen entsprechend zu aktualisieren, so dass diese mit dem Contao-Manager installiert werden kann. Wenn eine finanzielle Unterstützung notwenig ist, bitte ich um kurze PN, Danke.

**Comment by christianbarkowsky** [comment]
Wird erledigt.

**Comment by Schmidty2** [comment]
Hallo,
gibt es schon eine Zeitplan für die Contao 4.4.x-Kompatibilität?

**Comment by MacKP** [comment]
4.4.x wäre super ^^ Gibt es da schon einen Zeitplan?
@Schmidty2  wie hast du die manuell installiert? Dann mache ich das so lange auch bei mir, wenn du mir sagen kannst wie ;-)

Schon ok. Habs auch per Hand installiert:
1. Hier runter laden
2. Entpacken und Ordner in extended_checkbox umbenennen
3. in /system/modules/ rein kopieren
4. Cache löschen (Manager oder Console)
5. Install aufrufen
6. install-tool (contao/install/) noch DB-update
7. Sicherheitshalber noch im Backend (Systemwartung) die Symlinks neu generieren lassen

Scheint auf den esten Blick zu funktionieren. Falls ich Probleme finde melde ich die in eigenen Tickets.

Viele Grüße

**Comment by christianbarkowsky** [comment]
Ich versuche es in der nächsten Woche.

**Comment by Schmidty2** [comment]
Hallo, kannst Du schon sagen, wann das Ganze für Contao 4.4 veröffentlicht wird?

**Comment by christianbarkowsky** [comment]
@Schmidty2 dann zieh dir mal die dev und probiere mal.

**Comment by Schmidty2** [comment]
Danke für Deine Arbeit.
Wie kann ich die dev über den Contao-Manager oder Composer installieren?

**Comment by christianbarkowsky** [comment]
<img width="1173" alt="bildschirmfoto 2018-01-22 um 10 36 15" src="https://user-images.githubusercontent.com/1230547/35214061-2cf8e5a6-ff60-11e7-9917-afd6f3a9aa92.png">

**Comment by Schmidty2** [comment]
Hallo, es funktioniert nur mit dem Template *form_widget_extended_checkbox.html5*.
Beim Template *form_widget_extended_checkbox_without_label.html5* fehlt am Anfang der Codeblock
`<?php $this->block('field'); ?>` ,deshalb gibt es einen Fehler. Wenn man die Zeile hinzufügt (in Zeile 2) funktioniert dieses Template auch.

Ansonsten läuft die Erweiterung, ich konnte außer oben genanntem Fehler nichts feststellen. Zum Test wurde Contao 4.4.12 verwendet.

Noch eine Frage: Bei Contao 4 gibt es ja die Formularausgabe im Frontend mit Tabellen nicht mehr (zumindest fehlt die Checkbox bei den Formulareinstellungen). Könnte man dann in den Templates nicht den Teil mit der Tabellenausgabe entfernen?
Oder muss dieser wegen der Rückwärtskomplatibilität erhalten bleiben?

**Comment by Schmidty2** [comment]
Hallo, konntest Du das Ganze schon weiter bearbeiten?

**Comment by Schmidty2** [comment]
Hallo, wann wird die Erweiterung als finale Version veröffentlicht? Ist eine finanzielle Unterstützung notwendig?

**Comment by christianbarkowsky** [comment]
Endlich fertig. #sorry
