### ISSUE TITLE
Checkbox ignoriert Pflichtfeldeinstellungen

### ISSUE THREAD

**Issue by sevenfour66** [christianbarkowsky/contao-extended-checkbox#8]
Hallo,

erstmal DANKE für die Erweiterung. Obwohl die Checkbox nicht als Pflichtfeld gesetzt ist, ist ein Absenden des Formulars nicht möglich, ohne die Checkbox anzuklicken.

Contao Core: 4.4.54
extended_checkbox: 1.21

Gruß
sev

**Comment by christianbarkowsky** [comment]
Fehker behoben @sevenfour66
