### ISSUE TITLE
Wrong markup for mandatory

### ISSUE THREAD

**Issue by xApep** [christianbarkowsky/contao-extended-checkbox#9]
Mandatory field is generated in the wrong place; it should be at the end or beginning and not in the middle.

Output of the markup:
```
<span>
    <input type="checkbox" name="" id="" class="checkbox" value="1" required="" />
    <label id="" for="">
        <span class="invisible">Mandatory field </span>
        I agree with 
        <span class="mandatory">*</span>
        <a href="" title="" onclick="this.blur();return !window.open(this.href)">terms & conditions</a>
    </label>
</span>
```
and then you get _I agree with *terms & conditions_

Source of a problem: https://github.com/christianbarkowsky/contao-extended-checkbox/blob/32987fea8c3fddc95165a13594549ebf2ac94789/forms/FormCheckBoxExtended.php#L157

**Comment by christianbarkowsky** [comment]
Fixed. Thx @xApep for reporting. Thx for fixing @veronikaplenta
